### ISSUE TITLE
Creates datastorage files for multiple versions (case) of user accounts.

### ISSUE THREAD

**Issue by Cat5TV** [minetest-technic/datastorage#2]
When a user logs into Minetest with a different type case than their username, datastorage creates a new file rather than using the existing one.

Eg., if my user account is coolguy and I login as Coolguy or COOLGUY, I'll now have:
datastorage_coolguy.data
datastorage_Coolguy.data
and
datastorage_COOLGUY.data

Cheers in advance for the fix  :)

**Comment by ShadowNinja** [comment]
These are in fact three completely separate players with separate inventories, passwords, etc.  This is correct behavior until Minetest switches to a case-insensitive system.
